package cn.uc.yiqibang.dao;

import cn.uc.yiqibang.bean.Provinces;

public interface ProvincesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provinces
     *
     * @mbggenerated Fri Nov 10 20:53:12 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provinces
     *
     * @mbggenerated Fri Nov 10 20:53:12 CST 2017
     */
    int insert(Provinces record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provinces
     *
     * @mbggenerated Fri Nov 10 20:53:12 CST 2017
     */
    int insertSelective(Provinces record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provinces
     *
     * @mbggenerated Fri Nov 10 20:53:12 CST 2017
     */
    Provinces selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provinces
     *
     * @mbggenerated Fri Nov 10 20:53:12 CST 2017
     */
    int updateByPrimaryKeySelective(Provinces record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provinces
     *
     * @mbggenerated Fri Nov 10 20:53:12 CST 2017
     */
    int updateByPrimaryKey(Provinces record);
}